### ISSUE TITLE
feat(bonus): Implement animated transitions between views

### ISSUE THREAD

**Issue by kamekaioken** [kheder-codes/dragon-ball-attack-radar#25]
(Optional) Use CSS transitions or a library compatible with React (like Framer Motion) to add smooth visual transitions when switching between `AttackList` and `AttackDetail` views in the `App` component.\n\n**Acceptance Criteria:**\n- AC1: Switching views has a smooth visual transition (e.g., fade).\n- AC2: Animations are brief and non-disruptive.

**Comment by kamekaioken** [comment]
# Info: Use General Project Context for LLMs

For various Large Language Models (LLMs) intended to assist with this project, you can use the general project context.

The relevant information can be found in the file:
[General Project Context](https://github.com/kheder-codes/dragon-ball-attack-radar/blob/main/prompts/general_context_prompt.md)

Please consider using this context to help improve the accuracy and relevance of LLM responses related to the project.

**Comment by kamekaioken** [comment]
**Technical Guidance for Issue #25: feat(bonus): Implement animated transitions between views**

*This requires adding a library or using CSS transitions. We'll outline the CSS transition approach as it's simpler.*

**1. Using CSS Transitions:**

* **Identify Transitioning Elements:** The main switch happens in `App.tsx` between rendering the list view (`<>...</>`) and the detail view (`<AttackDetail />`). We need wrapper elements around these that we can style.
* **Modify `App.tsx` Structure:** Wrap the list view and detail view in separate `div`s. Add classes based on whether the detail view is active. Use an additional state to manage the animation timing correctly, especially for the exit animation.

    ```typescript
    // src/App.tsx
    import React, { useState, useEffect, useMemo } from 'react';
    import './App.css'; // Import App.css for transition styles
    // ... other imports ...
    import { AttackItemData } from './types/attackTypes'; // Ensure type import
    import AttackList from './components/AttackList';
    import AttackDetail from './components/AttackDetail';

    // ... transformFightData function ...
    // ... sortButtonStyles helper ...

    function App() {
        // ... states (originalAttacks, searchTerm, selectedSaga, selectedAttack, loading, sortKey) ...
        const [originalAttacks, setOriginalAttacks] = useState<AttackItemData[]>([]);
        const [searchTerm, setSearchTerm] = useState<string>('');
        const [selectedSaga, setSelectedSaga] = useState<string>('');
        const [selectedAttack, setSelectedAttack] = useState<AttackItemData | null>(null);
        const [loading, setLoading] = useState<boolean>(true);
        const [sortKey, setSortKey] = useState<SortKey>('default');

        // --- Animation State ---
        // Tracks if the detail view *should be* rendered (even if fading out)
        const [isDetailMounted, setIsDetailMounted] = useState(false);
        // Tracks if the detail view should have the 'visible' class (for fade-in/out)
        const [isDetailVisible, setIsDetailVisible] = useState(false);
        const animationDuration = 300; // ms, match CSS transition duration

        // ... useEffect to load data ...
         useEffect(() => {
            const timer = setTimeout(() => { /* load data */ setLoading(false); }, 500);
            return () => clearTimeout(timer);
         }, []);

        // ... uniqueSagas calculation ...
         const uniqueSagas = useMemo(() => { /* ... */ }, [originalAttacks]);

        // ... handlers (handleSearchChange, handleSagaChange, handleSortChange) ...
         const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => { /* ... */ };
         const handleSagaChange = (event: React.ChangeEvent<HTMLSelectElement>) => { /* ... */ };
         const handleSortChange = (key: SortKey) => { setSortKey(key); };


        // --- Updated Selection/Navigation Handlers for Animation ---
        const handleAttackSelect = (attack: AttackItemData) => {
            setSelectedAttack(attack); // Set the data immediately
            setIsDetailMounted(true);  // Mount the detail component wrapper
            // Use a tiny timeout to allow mounting before triggering fade-in
            setTimeout(() => {
                setIsDetailVisible(true); // Add 'visible' class to start fade-in
            }, 10); // Small delay
        };

        const handleGoBack = () => {
            setIsDetailVisible(false); // Remove 'visible' class to start fade-out
            // Wait for animation to finish before unmounting and clearing data
            setTimeout(() => {
                setIsDetailMounted(false); // Unmount the detail component wrapper
                setSelectedAttack(null); // Clear the data
            }, animationDuration); // Use the defined duration
        };
        // --- End Updated Handlers ---


        // ... getProcessedAttacks function ...
         const getProcessedAttacks = (): AttackItemData[] => { /* ... filter/sort logic ... */ };
         const displayedAttacks = getProcessedAttacks();


         if (loading) { /* ... return loading indicator ... */ }

        return (
            <div className="App" style={{ padding: '1rem' }}>
                <h1>Dragon Ball Attack Viewer</h1>

                {/* --- View Container --- */}
                {/* Using position relative allows absolute positioning inside for transitions */}
                <div className="view-container" style={{ position: 'relative' }}>

                    {/* List View Wrapper - Apply classes based on detail visibility */}
                    {/* Always mounted, but visibility controlled by class */}
                    <div
                        className={`list-view ${isDetailVisible ? 'view-hidden' : 'view-visible'}`}
                        style={{ width: '100%' }} // Ensure it takes space initially
                    >
                         <div className="controls-area" /* ... */ >
                             <input /* ... */ />
                             <select /* ... */ />
                             <div className="sort-controls" /* ... */ >
                                {/* ... sort buttons ... */}
                             </div>
                         </div>
                         <AttackList
                            attacks={displayedAttacks}
                            onAttackSelect={handleAttackSelect}
                         />
                    </div>

                    {/* Detail View Wrapper - Mount only when needed, apply classes */}
                    {isDetailMounted && selectedAttack && ( // Mount wrapper only if needed
                       <div
                           className={`detail-view ${isDetailVisible ? 'view-visible' : 'view-hidden'}`}
                           style={{ width: '100%' }} // Ensure it takes space
                       >
                           <AttackDetail
                               selectedAttack={selectedAttack}
                               onGoBack={handleGoBack}
                           />
                       </div>
                    )}
                </div>
                {/* --- End View Container --- */}
            </div>
        );
    }
    export default App;
    ```
* **Add/Update CSS Styles (`src/App.css`):** Define the transition properties and visibility states.

    ```css
    /* src/App.css */

    /* Styles for the main App container if needed */
    .App {
      /* ... */
    }

    /* Container to manage the positioning and overflow of views */
    .view-container {
      position: relative;
      min-height: 400px; /* Give it some minimum height */
    }

    .list-view,
    .detail-view {
      /* Smooth transition for opacity and transform */
      transition: opacity 300ms ease-in-out, transform 300ms ease-in-out;
      width: 100%;
      /* Position absolute allows views to overlap during transition */
      position: absolute;
      top: 0;
      left: 0;
    }

    /* State when a view should be visible */
    .view-visible {
      opacity: 1;
      transform: translateX(0);
      pointer-events: auto; /* Allow interaction */
      position: relative; /* Back to normal flow when visible */
    }

    /* State when a view should be hidden */
    .view-hidden {
      opacity: 0;
      pointer-events: none; /* Prevent interaction when hidden/fading */
      position: absolute; /* Keep in DOM but out of flow */
    }

    /* Specific starting/ending points for transitions */
    .list-view.view-hidden {
      transform: translateX(-30px); /* Slide list out to the left */
    }

    .detail-view.view-hidden {
      transform: translateX(30px); /* Start detail view off-screen to the right */
    }

    /* Ensure the list view starts in the correct position */
    .list-view.view-visible {
        transform: translateX(0);
    }
     /* Ensure the detail view ends in the correct position */
    .detail-view.view-visible {
         transform: translateX(0);
    }

    /* Add styles for controls-area, sort-controls, buttons etc. if not using modules */
    .controls-area {
        margin-bottom: 1.5rem;
        padding: 1rem;
        background: #f0f0f0;
        border-radius: 8px;
        display: flex;
        gap: 1rem;
        flex-wrap: wrap;
        align-items: center;
    }
     .sort-controls {
        margin-left: auto;
        display: flex;
        gap: 0.5rem;
        flex-wrap: wrap;
    }


    ```
* **Explanation:**
    * We introduce `isDetailMounted` and `isDetailVisible` states.
    * `handleAttackSelect`: Sets data, mounts the detail wrapper (`isDetailMounted=true`), then shortly after makes it visible (`isDetailVisible=true`) to trigger the fade/slide-in.
    * `handleGoBack`: Makes the detail view invisible (`isDetailVisible=false`) to trigger fade/slide-out, then *after* the animation duration, it unmounts the wrapper (`isDetailMounted=false`) and clears the data (`setSelectedAttack(null)`).
    * CSS classes (`view-visible`, `view-hidden`) control `opacity` and `transform`.
    * `position: absolute` is used on the views during transition to allow them to overlap smoothly without affecting layout drastically. `position: relative` on the container keeps them contained.

**Check the app (CSS method):** Clicking an item should cause the list to fade/slide out as the detail view fades/slides in. Clicking "Back" should reverse the animation smoothly.

**Acceptance Criteria Met If:**
* Switching from the list view to the detail view involves a smooth visual transition (e.g., fade-in/out, slide).
* Switching back from the detail view to the list view also has a smooth transition.
* Animations are reasonably quick (e.g., ~300ms) and do not significantly impede user interaction.
