### ISSUE TITLE
Add basic CSS styling for the list view

### ISSUE THREAD

**Issue by kamekaioken** [kheder-codes/dragon-ball-attack-radar#7]
Create a CSS file (e.g., `AttackList.module.css` for CSS Modules, or a global `index.css`) and import/use it. Add simple styles to make the list items (`AttackItem`) distinct and readable (e.g., borders, padding, margin). Style the overall list container (`AttackList`) if needed. Goal is clarity.\n\n**Acceptance Criteria:**\n- AC1: Basic CSS rules are applied to `AttackList` and/or `AttackItem` components.\n- AC2: List items are visually separated.\n- AC3: The list is reasonably formatted and readable.

**Comment by kamekaioken** [comment]
# Info: Use General Project Context for LLMs

For various Large Language Models (LLMs) intended to assist with this project, you can use the general project context.

The relevant information can be found in the file:
[General Project Context](https://github.com/kheder-codes/dragon-ball-attack-radar/blob/main/prompts/general_context_prompt.md)

Please consider using this context to help improve the accuracy and relevance of LLM responses related to the project.

**Comment by kamekaioken** [comment]
**Technical Guidance for Issue #7: Add basic CSS styling for the list view**

**Using CSS Modules (Recommended)**

1.  **Create CSS Module files:**
    * `src/components/AttackList.module.css`
    * `src/components/AttackItem.module.css`
2.  **Add styles to `AttackList.module.css`:**
    ```css
    /* src/components/AttackList.module.css */
    .listContainer {
      padding: 1rem;
    }

    .list {
      list-style: none;
      padding: 0;
      margin: 0;
      display: grid;
      /* Responsive grid: columns are at least 280px wide */
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: 1.5rem; /* Space between items */
    }

    .noResults {
        text-align: center;
        color: #555;
        margin-top: 2rem;
        font-style: italic;
    }
    ```
3.  **Add styles to `AttackItem.module.css`:**
    ```css
    /* src/components/AttackItem.module.css */
    .item {
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 1rem;
      background-color: #f9f9f9;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
      transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
      cursor: pointer; /* Indicate interactivity */
      display: flex; /* Use flexbox for better layout */
      flex-direction: column; /* Stack elements vertically */
      align-items: center; /* Center content horizontally */
      text-align: center;
    }

    .item:hover {
      transform: translateY(-4px);
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .attackName {
      font-size: 1.2em;
      font-weight: bold;
      margin-bottom: 0.5rem;
      color: #333;
    }

    .opponentInfo {
      font-size: 0.95em;
      color: #444;
      margin-bottom: 0.5rem;
    }

     .sagaInfo {
      font-size: 0.8em;
      color: #666;
      margin-bottom: 1rem;
      font-style: italic;
    }

    .imagesContainer {
        display: flex;
        justify-content: center; /* Center images horizontally */
        gap: 1rem; /* Space between images */
        margin-top: auto; /* Push images to the bottom if needed */
        padding-top: 0.5rem; /* Space above images */
        width: 100%; /* Ensure container takes full width */
    }

    .image {
      width: 60px; /* Fixed width */
      height: 60px; /* Fixed height */
      object-fit: contain; /* Scale while preserving aspect ratio */
      background-color: #fff; /* Add a background for transparency */
      border-radius: 4px;
      border: 1px solid #eee;
    }
    ```
4.  **Import and apply styles in `AttackList.tsx`:**
    ```typescript
    // src/components/AttackList.tsx
    import React from 'react';
    import { AttackItemData } from '../types/attackTypes';
    import AttackItem from './AttackItem';
    import styles from './AttackList.module.css'; // Import CSS Module

    interface AttackListProps {
      attacks: AttackItemData[];
      // onAttackSelect: (attack: AttackItemData) => void;
    }

    const AttackList: React.FC<AttackListProps> = ({ attacks }) => {
      return (
        <div className={styles.listContainer}> {/* Use imported style */}
          <h2>Attacks Used</h2>
          {attacks.length === 0 ? (
            <p className={styles.noResults}>No attacks match your filter criteria.</p> {/* Style the message */}
          ) : (
            <ul className={styles.list}> {/* Use imported style */}
              {attacks.map((attack) => (
                <AttackItem key={attack.id} attackData={attack} /* onAttackSelect={onAttackSelect} */ />
              ))}
            </ul>
          )}
        </div>
      );
    };

    export default AttackList;
    ```
5.  **Import and apply styles in `AttackItem.tsx`:**
    ```typescript
    // src/components/AttackItem.tsx
    import React from 'react';
    import { AttackItemData } from '../types/attackTypes';
    import styles from './AttackItem.module.css'; // Import CSS Module

    interface AttackItemProps {
      attackData: AttackItemData;
      // onAttackSelect: (attack: AttackItemData) => void;
    }

    const AttackItem: React.FC<AttackItemProps> = ({ attackData }) => {
      const attackImagePath = `${process.env.PUBLIC_URL}/images/${attackData.attackImageSource}`;
      const opponentImagePath = `${process.env.PUBLIC_URL}/images/${attackData.opponentImageSource}`;

      const handleImageError = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
        e.currentTarget.style.display = 'none';
      };

      const handleClick = () => {
        // Call onAttackSelect here when added
        // if (onAttackSelect) {
        //   onAttackSelect(attackData);
        // }
        console.log('Item clicked:', attackData.id); // Placeholder for click action
      };

      return (
        <li className={styles.item} onClick={handleClick}> {/* Use imported style and add onClick */}
          <h4 className={styles.attackName}>{attackData.attackName}</h4> {/* Use style */}
          <p className={styles.opponentInfo}>vs. {attackData.opponentName}</p> {/* Use style */}
          <p className={styles.sagaInfo}>Saga: {attackData.saga}</p> {/* Use style */}
          <div className={styles.imagesContainer}> {/* Container for images */}
             <img
               src={attackImagePath}
               alt={attackData.attackName}
               className={styles.image} // Use style
               onError={handleImageError}
             />
             <img
               src={opponentImagePath}
               alt={attackData.opponentName}
               className={styles.image} // Use style
               onError={handleImageError}
             />
          </div>
        </li>
      );
    };

    export default AttackItem;
    ```
6.  **Check the app:** The list should now be displayed in a responsive grid with styled cards for each attack, including hover effects.

**Acceptance Criteria Met If:**
* CSS rules (via modules or global CSS) are applied to `AttackList` and `AttackItem`.
* List items are visually distinct and arranged (e.g., in a grid).
* Basic hover effects and spacing improve readability and visual appeal.
